# https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_webflux_server_configuration

# logging:
#   level:
#     slim.ai: DEBUG
#     org.springframework.ai: TRACE

# Using spring-ai-starter-mcp-server-webmvc
spring:
  ai:
    mcp:
      server:
        name: github-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        sse-message-endpoint: /mcp/messages

server:
  port: 8090

mcpServers:
  github:
    env:
      GITHUB_URL: https://api.github.com
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USERNAME: ${GITHUB_USERNAME}

---
spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          github:
            url: ${mcpServers.github.env.GITHUB_URL}
